version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  run_tests:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run: java --version
      - run: node --version
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

workflows:
  build_and_test:
    jobs:
      - run_tests
